dist: trusty
sudo: false
language: node_js
node_js: 8.6.0
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.2.1
- export PATH=$HOME/.yarn/bin:$PATH
- yarn global add greenkeeper-lockfile@1
cache:
  yarn: true
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
deploy:
  provider: npm
  email: rtsao@uber.com
  api_key:
    secure: 0qSHKknezIvnJDqvTUofrXmXoGi3/f3Sfj/evKZHUclVOlk80YruaVFwt6OC4bZqQIlSld1rCnCIFubo+QgPgp/zO+U5vJ+X9s9qeLXzNvCO7T/fAZIDD0mtM3nEXuIm0Kv2/qgLv3D9SrmwniMUoC34+PnjPFFuHdwfXZpoVoS/IhzhA6O9TE8irwZwg/stjz1hcbEdEYve4w+WgDfrZn/uIgYOxijTNUm6LerpRp3uu+XdmOqr3mhao0WYvdyEeQLZKxd7QS363sWX1HClNNzxtNGFI+d+L9Z+2+6FU82R6ujgl9evuFqOpegXIcsf5tN3LlCSQeGbyvyAOYXxaZlFnVjzSUMSSAzWPgKpI6ril9MCB0Xzu0Te8HvQXA9qmYdi9Binhk+MmnVNkHBz/LB8aKy4rR/IAeXlTHyP+a06t3rBkxQ2zmYbayYWiwH/q4/b31BW7iXTBgx7/p/2qBc61Uqg9W7WCGqx4QxkRyGm/TbRVwzQRuV5cbwXAVF0dZ5z14IrvEfkICxEfALJbEbcz07/5jUgAG4dBth4m+lFGlxWQtSo1Qd5PvDd2Pt8ZNOSgFhhuP66e+e3h77CHOKghik2qSMguWEYHBmQ+Alja/i467Aaq1mbrCotPBJF0HerrUI0jFAMPTGNuGfX73oOEpwGsv/9PGbhRuI0f/Q=
  on:
    tags: true
    repo: uber-web/probot-app-pr-issue
